-- 0034_desktop_parity_followups_and_inventory.sql
--
-- Desktop-parity follow-ups (sales/POS) and Phase 05 inventory documents.
-- All additions are additive: existing invoices, POS tickets and inventory movements keep
-- their original meanings. New document tables are deliberately separate from the
-- append-only `inventory_transactions` ledger; documents describe user intent while the
-- ledger remains the sole stock-value authority.

-- ---------------------------------------------------------------------------
-- Sales / POS audit context
-- ---------------------------------------------------------------------------
ALTER TABLE sales_invoices
  ADD COLUMN IF NOT EXISTS cashier_id uuid REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE sales_invoices
  ADD COLUMN IF NOT EXISTS tax_type text NOT NULL DEFAULT 'simplified';

CREATE INDEX IF NOT EXISTS sales_invoices_cashier_idx
  ON sales_invoices (tenant_id, cashier_id, posted_at);

-- A movement can now state the unit the operator entered. `qty` remains the entered
-- quantity and `base_qty` remains the quantity carried by stock_balances.
ALTER TABLE inventory_transactions
  ADD COLUMN IF NOT EXISTS unit_id uuid REFERENCES units_of_measure(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS inventory_transactions_unit_idx
  ON inventory_transactions (tenant_id, item_id, unit_id);

-- Transfers preserve the unit chosen by the sender as well as the base quantity in the
-- ledger, so a carton transfer cannot silently become a one-piece transfer at receipt.
ALTER TABLE stock_transfer_lines
  ADD COLUMN IF NOT EXISTS unit_id uuid REFERENCES units_of_measure(id) ON DELETE RESTRICT;

-- ---------------------------------------------------------------------------
-- POS speed features: the desktop's eight hold slots and per-branch shortcut keys.
-- A recalled/cancelled hold remains as an audit record; the partial unique index makes a
-- slot reusable once it no longer has a live held ticket.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pos_held_tickets (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  slot smallint NOT NULL CHECK (slot BETWEEN 1 AND 8),
  status text NOT NULL DEFAULT 'held' CHECK (status IN ('held', 'recalled', 'cancelled')),
  payload jsonb NOT NULL DEFAULT '{}',
  held_at timestamptz NOT NULL DEFAULT now(),
  recalled_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version int NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS pos_held_tickets_live_slot_key
  ON pos_held_tickets (tenant_id, branch_id, user_id, slot)
  WHERE status = 'held';
CREATE INDEX IF NOT EXISTS pos_held_tickets_scope_idx
  ON pos_held_tickets (tenant_id, branch_id, user_id, status, held_at DESC);

CREATE TABLE IF NOT EXISTS pos_shortcut_items (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  slot smallint NOT NULL CHECK (slot BETWEEN 1 AND 48),
  item_id uuid NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version int NOT NULL DEFAULT 1,
  UNIQUE (tenant_id, branch_id, slot),
  UNIQUE (tenant_id, branch_id, item_id)
);
CREATE INDEX IF NOT EXISTS pos_shortcut_items_scope_idx
  ON pos_shortcut_items (tenant_id, branch_id, slot);

-- ---------------------------------------------------------------------------
-- Inventory documents (opening stock, stock receipt, stock issue and approved
-- adjustment). The document itself is mutable only while draft; posting writes immutable
-- ledger rows and one balanced journal entry generated by the service.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_documents (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  branch_id uuid NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  warehouse_id uuid NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
  number text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('opening', 'receipt', 'issue', 'adjustment')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'posted', 'voided', 'cancelled')),
  document_date date NOT NULL DEFAULT CURRENT_DATE,
  reason text,
  counter_account_id uuid REFERENCES accounts(id) ON DELETE RESTRICT,
  journal_entry_id uuid REFERENCES journal_entries(id) ON DELETE RESTRICT,
  notes text,
  posted_at timestamptz,
  voided_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version int NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS inventory_documents_tenant_number_key
  ON inventory_documents (tenant_id, number);
CREATE INDEX IF NOT EXISTS inventory_documents_scope_idx
  ON inventory_documents (tenant_id, branch_id, warehouse_id, kind, status, document_date DESC);

CREATE TABLE IF NOT EXISTS inventory_document_lines (
  id uuid PRIMARY KEY,
  document_id uuid NOT NULL REFERENCES inventory_documents(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  line_no integer NOT NULL,
  item_id uuid NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
  unit_id uuid NOT NULL REFERENCES units_of_measure(id) ON DELETE RESTRICT,
  quantity numeric(20,4) NOT NULL CHECK (quantity > 0),
  base_quantity numeric(20,4) NOT NULL CHECK (base_quantity > 0),
  unit_cost numeric(20,4) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  lot_id uuid REFERENCES item_lots(id) ON DELETE RESTRICT,
  serial_ids jsonb NOT NULL DEFAULT '[]',
  adjustment_direction text CHECK (adjustment_direction IN ('in', 'out')),
  note text,
  metadata jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version int NOT NULL DEFAULT 1,
  UNIQUE (document_id, line_no)
);
CREATE INDEX IF NOT EXISTS inventory_document_lines_item_idx
  ON inventory_document_lines (tenant_id, item_id);

-- ---------------------------------------------------------------------------
-- RLS: all tables that carry a tenant id enforce the same request-bound tenant boundary
-- as the rest of the cloud ERP.
-- ---------------------------------------------------------------------------
DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'pos_held_tickets',
    'pos_shortcut_items',
    'inventory_documents',
    'inventory_document_lines'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I', table_name || '_tenant_isolation', table_name);
    EXECUTE format(
      'CREATE POLICY %I ON %I USING (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::uuid)',
      table_name || '_tenant_isolation',
      table_name
    );
  END LOOP;
END $$;
