/* eslint-disable no-restricted-syntax, import/order */
import { Inject, Injectable } from '@nestjs/common';
import { and, desc, eq, isNull, sql } from 'drizzle-orm';

import { DomainError, errorCodes, newId } from '@erp/contracts';
import { journalEntries, journalEntryLines, parties, partyContacts, paymentAllocations, withTenantTx, type DatabaseHandle } from '@erp/database';

import { DATABASE_HANDLE } from '../../database/database.module.js';

export type PartyInput = { kind: 'customer' | 'supplier' | 'both'; name: string; legalName?: string; taxNo?: string; nationalId?: string; address?: Record<string, string | undefined>; phone?: string; email?: string; receivableAccountId?: string; payableAccountId?: string; creditLimit?: string; isOwner?: boolean; isContractor?: boolean; branchId?: string };
export type ContactInput = { name: string; role?: string; phone?: string; email?: string; isPrimary?: boolean };
export type AllocationInput = { partyId: string; voucherId?: string; invoiceKind: string; invoiceId: string; amount: string; invoiceTotal?: string; alreadyAllocated?: string };

@Injectable()
export class PartiesService {
  constructor(@Inject(DATABASE_HANDLE) private readonly database: DatabaseHandle) {}
  async list(tenantId: string, kind?: string) { return withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(parties).where(and(eq(parties.tenantId, tenantId), isNull(parties.deletedAt), kind ? eq(parties.kind, kind) : undefined)).orderBy(desc(parties.createdAt)).limit(100)); }
  async get(tenantId: string, id: string) { const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(parties).where(and(eq(parties.tenantId, tenantId), eq(parties.id, id), isNull(parties.deletedAt)))); return row; }
  async update(tenantId: string, id: string, input: Partial<PartyInput>) { await withTenantTx(this.database.db, tenantId, (tx) => tx.update(parties).set({ ...input, updatedAt: new Date(), version: sql`${parties.version} + 1` }).where(and(eq(parties.tenantId, tenantId), eq(parties.id, id), isNull(parties.deletedAt)))); return this.get(tenantId, id); }
  async create(tenantId: string, input: PartyInput) { const id = newId(); const code = await withTenantTx(this.database.db, tenantId, async (tx) => { const result = await tx.execute(sql`SELECT COALESCE(MAX(CAST(code AS INTEGER)), 0) + 1 AS next FROM parties WHERE tenant_id = ${tenantId} AND code ~ '^[0-9]+$'`); return String(Number((result.rows[0] as { next: string }).next).toString().padStart(6, '0')); }); await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(parties).values({ id, tenantId, code, ...input, creditLimit: input.creditLimit ?? '0' })); return this.get(tenantId, id); }
  async softDelete(tenantId: string, id: string) { const balance = await this.partyBalance(tenantId, id); if (balance.receivable !== '0' || balance.payable !== '0' || balance.open.length) throw new DomainError('PARTY_HAS_OPEN_BALANCE', 'Party has an open balance and cannot be deleted', 422); await withTenantTx(this.database.db, tenantId, (tx) => tx.update(parties).set({ deletedAt: new Date() }).where(and(eq(parties.tenantId, tenantId), eq(parties.id, id)))); }
  async contacts(tenantId: string, partyId: string) { return withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(partyContacts).where(and(eq(partyContacts.tenantId, tenantId), eq(partyContacts.partyId, partyId), isNull(partyContacts.deletedAt)))); }
  async addContact(tenantId: string, partyId: string, input: ContactInput) { const id = newId(); await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(partyContacts).values({ id, partyId, tenantId, ...input })); return this.contacts(tenantId, partyId); }
  async removeContact(tenantId: string, partyId: string, id: string) { await withTenantTx(this.database.db, tenantId, (tx) => tx.update(partyContacts).set({ deletedAt: new Date() }).where(and(eq(partyContacts.tenantId, tenantId), eq(partyContacts.partyId, partyId), eq(partyContacts.id, id)))); return this.contacts(tenantId, partyId); }
  async allocate(tenantId: string, input: AllocationInput) { const amount = Number(input.amount); const total = Number(input.invoiceTotal ?? Number.POSITIVE_INFINITY); const allocated = Number(input.alreadyAllocated ?? 0); if (!Number.isFinite(amount) || amount <= 0 || allocated + amount > total) throw new DomainError('ALLOCATION_EXCEEDS_OPEN_AMOUNT', 'Allocation exceeds the invoice open amount', 422); const id = newId(); await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(paymentAllocations).values({ id, tenantId, partyId: input.partyId, voucherId: input.voucherId, invoiceKind: input.invoiceKind, invoiceId: input.invoiceId, amount: input.amount })); return { id, ...input }; }
  async partyBalance(tenantId: string, partyId: string, asOf?: string) { const rows = await withTenantTx(this.database.db, tenantId, (tx) => tx.select({ accountId: journalEntryLines.accountId, debit: journalEntryLines.debit, credit: journalEntryLines.credit, date: journalEntries.date, entryId: journalEntries.id }).from(journalEntryLines).innerJoin(journalEntries, eq(journalEntryLines.entryId, journalEntries.id)).where(and(eq(journalEntryLines.tenantId, tenantId), eq(journalEntryLines.partyId, partyId), eq(journalEntries.status, 'posted'), asOf ? sql`${journalEntries.date} <= ${asOf}` : undefined))); const total = rows.reduce((sum, row) => sum + Number(row.debit) - Number(row.credit), 0).toFixed(4); const allocations = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(paymentAllocations).where(and(eq(paymentAllocations.tenantId, tenantId), eq(paymentAllocations.partyId, partyId)))); return { receivable: total, payable: '0.0000', open: rows.map((row) => ({ ...row, allocated: allocations.filter((a) => a.invoiceId === row.entryId).reduce((s, a) => s + Number(a.amount), 0).toFixed(4) })) }; }
  async assertCreditAvailable(tenantId: string, partyId: string, newAmount: string, override = false) { const party = await this.get(tenantId, partyId); if (!party) throw new DomainError(errorCodes.NOT_FOUND, 'Party not found', 404); if (!override && Number((await this.partyBalance(tenantId, partyId)).receivable) + Number(newAmount) > Number(party.creditLimit)) throw new DomainError('CREDIT_LIMIT_EXCEEDED', 'Credit limit exceeded', 422); return true; }
}
