/* eslint-disable no-restricted-syntax */
import { Inject, Injectable } from '@nestjs/common';
import { Decimal } from 'decimal.js';
import { and, eq, isNull } from 'drizzle-orm';
import { DomainError, newId } from '@erp/contracts';
import { marinaBookingAdditions, marinaBookings, marinaOperationPlanLines, marinaOperationPlans, marinaViolations, rentalInvoices, tenantSettings, vesselGroupPricing, vesselGroups, vesselOwners, vessels, withTenantTx, type DatabaseHandle } from '@erp/database';

import { DATABASE_HANDLE } from '../../database/database.module.js';
import { SalesService } from '../sales/sales.service.js';

import { calculateMarinaPeriod } from './marina-pricing.js';

@Injectable()
export class MarinaService {
  constructor(@Inject(DATABASE_HANDLE) private readonly database: DatabaseHandle, private readonly sales: SalesService) {}
  async ensureEnabled(tenantId: string) { const [flag] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(tenantSettings).where(and(eq(tenantSettings.tenantId, tenantId), eq(tenantSettings.key, 'pack.marina'))).limit(1)); if (flag && flag.value !== true && flag.value !== 'true') throw new DomainError('NOT_FOUND', 'Marina pack is disabled', 404); }
  async createGroup(tenantId: string, input: { name: string; code?: string }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(vesselGroups).values({ id: newId(), tenantId, ...input }).returning()); return row; }
  async price(tenantId: string, groupId: string, input: { periodKind: string; price: string; currency?: string }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(vesselGroupPricing).values({ id: newId(), tenantId, groupId, periodKind: input.periodKind, price: input.price, currency: input.currency ?? 'SAR' }).returning()); return row; }
  async createVessel(tenantId: string, input: { groupId?: string; code: string; name: string; capacity?: number; metadata?: Record<string, unknown> }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(vessels).values({ id: newId(), tenantId, groupId: input.groupId, code: input.code, name: input.name, capacity: input.capacity ?? 0, metadata: input.metadata ?? {} }).returning()); return row; }
  async addOwner(tenantId: string, vesselId: string, input: { partyId: string; percent: string }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(vesselOwners).values({ id: newId(), tenantId, vesselId, partyId: input.partyId, percent: input.percent }).returning()); return row; }
  async createBooking(tenantId: string, input: { branchId: string; partyId: string; vesselId: string; startsAt: string; endsAt: string; companions?: number; insuranceAmount?: string; metadata?: Record<string, unknown> }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(marinaBookings).values({ id: newId(), tenantId, branchId: input.branchId, partyId: input.partyId, vesselId: input.vesselId, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), companions: input.companions ?? 0, insuranceAmount: input.insuranceAmount ?? '0', metadata: input.metadata ?? {} }).returning()); return row; }
  async addBookingAddition(tenantId: string, bookingId: string, input: { description: string; amount: string }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(marinaBookingAdditions).values({ id: newId(), tenantId, bookingId, description: input.description, amount: input.amount }).returning()); return row; }
  async createRentalInvoice(tenantId: string, bookingId: string) { await this.ensureEnabled(tenantId); const [booking] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(marinaBookings).where(and(eq(marinaBookings.tenantId, tenantId), eq(marinaBookings.id, bookingId)))); if (!booking) throw new DomainError('BOOKING_NOT_FOUND', 'Booking not found', 404); const [vessel] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(vessels).where(and(eq(vessels.tenantId, tenantId), eq(vessels.id, booking.vesselId)))); const prices = vessel?.groupId ? await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(vesselGroupPricing).where(and(eq(vesselGroupPricing.tenantId, tenantId), eq(vesselGroupPricing.groupId, vessel.groupId!)))) : []; const hourly = prices.find((p) => p.periodKind === 'hour')?.price ?? '0'; const half = prices.find((p) => p.periodKind === 'half_hour')?.price; const offer = prices.find((p) => p.periodKind === 'offer')?.price; const periodAmount = calculateMarinaPeriod({ startsAt: booking.startsAt.toISOString(), endsAt: booking.endsAt.toISOString(), hourlyPrice: hourly, halfHourPrice: half, offerPrice: offer }); const additions = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(marinaBookingAdditions).where(and(eq(marinaBookingAdditions.tenantId, tenantId), eq(marinaBookingAdditions.bookingId, bookingId)))); const additionsAmount = additions.reduce((sum, line) => sum.plus(line.amount), new Decimal(0)); const total = new Decimal(periodAmount).plus(additionsAmount).plus(booking.insuranceAmount); const invoice = await this.sales.create(tenantId, { branchId: booking.branchId, partyId: booking.partyId, kind: 'sale', lines: [{ description: `Marina rental ${bookingId}`, quantity: '1', unitPrice: total.toFixed(4), taxRate: '0' }] }); const [rental] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(rentalInvoices).values({ id: newId(), tenantId, bookingId, salesInvoiceId: invoice.id, periodAmount, additionsAmount: additionsAmount.toFixed(4), insuranceAmount: booking.insuranceAmount, total: total.toFixed(4), metadata: { companions: booking.companions, source: 'booking' } }).returning()); return { data: { ...rental, salesInvoiceId: invoice.id } }; }
  async violation(tenantId: string, input: { vesselId?: string; bookingId?: string; partyId?: string; violationDate: string; amount?: string; description: string }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(marinaViolations).values({ id: newId(), tenantId, ...input, amount: input.amount ?? '0' }).returning()); return row; }
  async plan(tenantId: string, input: { groupId?: string; planDate: string; name: string; lines?: Array<{ vesselId: string; periodLabel?: string; metadata?: Record<string, unknown> }> }) { await this.ensureEnabled(tenantId); const id = newId(); await withTenantTx(this.database.db, tenantId, async (tx) => { await tx.insert(marinaOperationPlans).values({ id, tenantId, groupId: input.groupId, planDate: input.planDate, name: input.name }); if (input.lines?.length) await tx.insert(marinaOperationPlanLines).values(input.lines.map((line, index) => ({ planId: id, tenantId, lineNo: index + 1, vesselId: line.vesselId, periodLabel: line.periodLabel, metadata: line.metadata ?? {} }))); }); return { id }; }
  async list(tenantId: string) { await this.ensureEnabled(tenantId); return { groups: await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(vesselGroups).where(and(eq(vesselGroups.tenantId, tenantId), isNull(vesselGroups.deletedAt)))), vessels: await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(vessels).where(and(eq(vessels.tenantId, tenantId), isNull(vessels.deletedAt)))) }; }
}
