import { createHash } from 'node:crypto';

import { Inject, Injectable } from '@nestjs/common';
import { Decimal } from 'decimal.js';
import { and, eq, gte, isNull, lte, or, sql } from 'drizzle-orm';
import { DomainError, newId } from '@erp/contracts';
import { attendanceLogs, departments, employees, jobs, payrollRunLines, payrollRuns, salaryAdjustments, tenantSettings, withTenantTx, type DatabaseHandle, type Employee } from '@erp/database';

import { DATABASE_HANDLE } from '../../database/database.module.js';
import { AccountingService, type JournalLineInput } from '../accounting/accounting.service.js';
import { TreasuryService } from '../treasury/treasury.service.js';

import { calculatePayrollLine } from './payroll-calculator.js';

export type DepartmentInput = { code: string; name: string; branchId?: string };
export type JobInput = { code: string; name: string };
export type EmployeeInput = { employeeNo: string; name: string; branchId?: string; departmentId?: string; jobId?: string; membershipId?: string; hireDate?: string; salaryComponents?: Record<string, string>; bank?: Record<string, string | undefined>; salaryExpenseAccountId?: string; salaryPayableAccountId?: string; costCenterId?: string };
export type AdjustmentInput = { employeeId: string; kind: 'addition' | 'deduction'; componentCode: string; valueText: string; startsOn: string; endsOn?: string; recurring?: boolean; subFromSalary?: boolean; cashLocationId?: string; reason?: string };
export type RunInput = { yearMonth: string; periodId?: string; currency?: string; unpaidDaysByEmployee?: Record<string, number> };
export type PostRunInput = { journalEntryId?: string; branchId?: string; fiscalPeriodId?: string; journalLines?: JournalLineInput[] };
export type PayRunInput = { branchId: string; cashLocationId: string; method?: 'cash' | 'cheque' | 'bank_transfer' | 'card'; fiscalPeriodId?: string };

@Injectable()
export class HrmService {
  constructor(@Inject(DATABASE_HANDLE) private readonly database: DatabaseHandle, private readonly accounting: AccountingService, private readonly treasury: TreasuryService) {}

  async ensureEnabled(tenantId: string) { const [flag] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(tenantSettings).where(and(eq(tenantSettings.tenantId, tenantId), eq(tenantSettings.key, 'pack.hrm'))).limit(1)); if (flag && flag.value !== true && flag.value !== 'true') throw new DomainError('NOT_FOUND', 'HRM pack is disabled for this tenant', 404); }
  async listDepartments(tenantId: string) { await this.ensureEnabled(tenantId); return withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(departments).where(eq(departments.tenantId, tenantId)).orderBy(departments.code)); }
  async createDepartment(tenantId: string, input: DepartmentInput) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(departments).values({ id: newId(), tenantId, code: input.code, name: input.name, branchId: input.branchId }).returning()); return row; }
  async listJobs(tenantId: string) { await this.ensureEnabled(tenantId); return withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(jobs).where(eq(jobs.tenantId, tenantId)).orderBy(jobs.code)); }
  async createJob(tenantId: string, input: JobInput) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(jobs).values({ id: newId(), tenantId, code: input.code, name: input.name }).returning()); return row; }

  async listEmployees(tenantId: string) { await this.ensureEnabled(tenantId); const rows = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(employees).where(and(eq(employees.tenantId, tenantId), isNull(employees.deletedAt))).orderBy(employees.employeeNo)); return rows.map(maskEmployee); }
  async createEmployee(tenantId: string, input: EmployeeInput) { await this.ensureEnabled(tenantId); validateComponents(input.salaryComponents ?? {}); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(employees).values({ id: newId(), tenantId, employeeNo: input.employeeNo, name: input.name, branchId: input.branchId, departmentId: input.departmentId, jobId: input.jobId, membershipId: input.membershipId, hireDate: input.hireDate, salaryComponents: input.salaryComponents ?? {}, bank: input.bank ?? {}, salaryExpenseAccountId: input.salaryExpenseAccountId, salaryPayableAccountId: input.salaryPayableAccountId, costCenterId: input.costCenterId }).returning()); return row ? maskEmployee(row) : undefined; }

  async importAttendanceCsv(tenantId: string, csv: string) { await this.ensureEnabled(tenantId); const rows = parseAttendance(csv); let inserted = 0; let skipped = 0; await withTenantTx(this.database.db, tenantId, async (tx) => { for (const row of rows) { const fingerprint = attendanceFingerprint(row); const result = await tx.execute(sql`INSERT INTO attendance_logs (id, tenant_id, machine, enroll, punch_at, direction, fingerprint, payload) VALUES (${newId()}, ${tenantId}, ${row.machine}, ${row.enroll}, ${new Date(row.datetime)}, ${row.inout}, ${fingerprint}, ${JSON.stringify(row)}::jsonb) ON CONFLICT (tenant_id, fingerprint) DO NOTHING RETURNING id`); if (rowsOf(result).length) inserted += 1; else skipped += 1; } }); return { data: { inserted, skipped, parsed: rows.length } }; }

  async attendanceSummary(tenantId: string, enroll: string, from: string, to: string) { await this.ensureEnabled(tenantId); const rows = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(attendanceLogs).where(and(eq(attendanceLogs.tenantId, tenantId), eq(attendanceLogs.enroll, enroll), gte(attendanceLogs.punchAt, new Date(from)), lte(attendanceLogs.punchAt, new Date(to)))).orderBy(attendanceLogs.punchAt)); let minutes = new Decimal(0); let open: Date | undefined; for (const row of rows) { if (row.direction === 'in') open = row.punchAt; else if (row.direction === 'out' && open) { minutes = minutes.plus(new Decimal(row.punchAt.getTime() - open.getTime()).div(60_000)); open = undefined; } } return { data: { enroll, punches: rows.length, workingHours: minutes.div(60).toFixed(2), method: 'naive in/out pairing; no RC-10 evaluation engine' } }; }

  async createAdjustment(tenantId: string, input: AdjustmentInput) { await this.ensureEnabled(tenantId); if (new Decimal(input.valueText).lte(0)) throw new DomainError('VALIDATION_FAILED', 'Adjustment value must be positive', 422); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(salaryAdjustments).values({ id: newId(), tenantId, employeeId: input.employeeId, kind: input.kind, componentCode: input.componentCode, valueText: input.valueText, startsOn: input.startsOn, endsOn: input.endsOn, recurring: input.recurring ?? false, subFromSalary: input.subFromSalary ?? input.kind === 'deduction', cashLocationId: input.cashLocationId, reason: input.reason }).returning()); return row; }
  async approveAdjustment(tenantId: string, id: string) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.update(salaryAdjustments).set({ status: 'approved', updatedAt: new Date() }).where(and(eq(salaryAdjustments.tenantId, tenantId), eq(salaryAdjustments.id, id), eq(salaryAdjustments.status, 'draft'))).returning()); if (!row) throw new DomainError('NOT_FOUND', 'Draft adjustment not found', 404); return row; }

  async preview(tenantId: string, input: RunInput) { await this.ensureEnabled(tenantId); const staff = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(employees).where(and(eq(employees.tenantId, tenantId), eq(employees.status, 'active'), isNull(employees.deletedAt)))); const activeAdjustments = await this.adjustmentsForMonth(tenantId, input.yearMonth); const lines = staff.map((employee) => calculatePayrollLine({ id: employee.id, name: employee.name, components: employee.salaryComponents, unpaidDays: input.unpaidDaysByEmployee?.[employee.id] ?? 0, adjustments: activeAdjustments.filter((entry) => entry.employeeId === employee.id).map((entry) => ({ kind: entry.kind as 'addition' | 'deduction', valueText: entry.valueText })) })); return { data: { yearMonth: input.yearMonth, employeeCount: lines.length, netPayable: sumLines(lines.map((line) => line.net)), lines } }; }

  async createRun(tenantId: string, input: RunInput) { const preview = await this.preview(tenantId, input); const id = newId(); await withTenantTx(this.database.db, tenantId, async (tx) => { await tx.insert(payrollRuns).values({ id, tenantId, yearMonth: input.yearMonth, periodId: input.periodId, currency: input.currency ?? 'SAR', summary: { preview: preview.data } }); if (preview.data.lines.length) await tx.insert(payrollRunLines).values(preview.data.lines.map((line, index) => ({ runId: id, lineNo: index + 1, tenantId, employeeId: line.employeeId, components: line.components, additions: line.additions, deductions: line.deductions, gross: line.gross, net: line.net, status: 'draft', payslipHtml: payslipHtml(input.yearMonth, line.employeeName, line.net) }))); }); return this.readRun(tenantId, id); }
  async readRun(tenantId: string, id: string) { await this.ensureEnabled(tenantId); const [run] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(payrollRuns).where(and(eq(payrollRuns.tenantId, tenantId), eq(payrollRuns.id, id))).limit(1)); if (!run) throw new DomainError('NOT_FOUND', 'Payroll run not found', 404); const lines = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(payrollRunLines).where(and(eq(payrollRunLines.tenantId, tenantId), eq(payrollRunLines.runId, id))).orderBy(payrollRunLines.lineNo)); return { data: { ...run, lines } }; }
  async listRuns(tenantId: string) { await this.ensureEnabled(tenantId); return { data: await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(payrollRuns).where(eq(payrollRuns.tenantId, tenantId)).orderBy(payrollRuns.yearMonth)) }; }
  async postRun(tenantId: string, id: string, input: PostRunInput = {}) { await this.ensureEnabled(tenantId); const current = await this.readRun(tenantId, id); if (current.data.status !== 'draft') throw new DomainError('PAYROLL_RUN_IMMUTABLE', 'Only draft payroll runs can be posted', 409); let journalEntryId = input.journalEntryId; if (!journalEntryId && input.journalLines?.length && input.branchId && (input.fiscalPeriodId ?? current.data.periodId)) { const journal = await this.accounting.postJournal(tenantId, { branchId: input.branchId, fiscalPeriodId: input.fiscalPeriodId ?? current.data.periodId!, date: new Date().toISOString().slice(0, 10), description: `Payroll ${current.data.yearMonth}`, lines: input.journalLines }); if (!journal) throw new DomainError('INTERNAL', 'Payroll journal was not created', 500); journalEntryId = journal.id; } await withTenantTx(this.database.db, tenantId, (tx) => tx.update(payrollRuns).set({ status: 'posted', journalEntryId, postedAt: new Date(), updatedAt: new Date() }).where(and(eq(payrollRuns.tenantId, tenantId), eq(payrollRuns.id, id)))); return this.readRun(tenantId, id); }
  async payRun(tenantId: string, id: string, input: PayRunInput) { await this.ensureEnabled(tenantId); const current = await this.readRun(tenantId, id); if (current.data.status !== 'posted') throw new DomainError('PAYROLL_RUN_NOT_POSTED', 'Only posted payroll runs can be paid', 409); const payValue = sumLines(current.data.lines.map((line) => line.net)); const voucher = await this.treasury.createVoucher(tenantId, { branchId: input.branchId, kind: 'payment', subtype: 'salary', date: new Date().toISOString().slice(0, 10), cashLocationId: input.cashLocationId, method: input.method ?? 'cash', amount: payValue, netAmount: payValue, idempotencyKey: `payroll:${id}` }); const posted = voucher?.id ? await this.treasury.postVoucher(tenantId, voucher.id, { fiscalPeriodId: input.fiscalPeriodId }) : undefined; await withTenantTx(this.database.db, tenantId, (tx) => tx.update(payrollRuns).set({ status: 'paid', voucherId: posted?.id, paidAt: new Date(), updatedAt: new Date() }).where(and(eq(payrollRuns.tenantId, tenantId), eq(payrollRuns.id, id)))); return this.readRun(tenantId, id); }
  async reverseRun(tenantId: string, id: string, reason: string) { await this.ensureEnabled(tenantId); if (!reason.trim()) throw new DomainError('VALIDATION_FAILED', 'Reversal reason is required', 422); const current = await this.readRun(tenantId, id); if (current.data.status !== 'posted' && current.data.status !== 'paid') throw new DomainError('PAYROLL_REVERSAL_INVALID', 'Only posted or paid runs can be reversed', 409); await withTenantTx(this.database.db, tenantId, (tx) => tx.update(payrollRuns).set({ status: 'reversed', reversedAt: new Date(), reversalReason: reason, updatedAt: new Date() }).where(and(eq(payrollRuns.tenantId, tenantId), eq(payrollRuns.id, id)))); return this.readRun(tenantId, id); }

  private async adjustmentsForMonth(tenantId: string, yearMonth: string) { const start = `${yearMonth}-01`; const end = `${yearMonth}-31`; return withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(salaryAdjustments).where(and(eq(salaryAdjustments.tenantId, tenantId), eq(salaryAdjustments.status, 'approved'), lte(salaryAdjustments.startsOn, end), or(isNull(salaryAdjustments.endsOn), gte(salaryAdjustments.endsOn, start)) ?? sql`true`))); }
}

function validateComponents(components: Record<string, string>) { for (const entry of Object.entries(components)) if (!new Decimal(entry[1] || '0').isFinite()) throw new DomainError('VALIDATION_FAILED', `Invalid salary component ${entry[0]}`, 422); }
function maskEmployee(employee: Employee) { const bank = employee.bank ?? {}; return { ...employee, bank: { ...bank, iban: maskIban(bank.iban) } }; }
function maskIban(value: string | undefined) { return value ? `${value.slice(0, 4)}********${value.slice(-4)}` : undefined; }
function parseAttendance(csv: string): Array<{ machine: string; enroll: string; datetime: string; inout: string }> { const lines = csv.trim().split(/\r?\n/).filter(Boolean); return lines.slice(lines[0]?.toLowerCase().includes('machine') ? 1 : 0).map((line) => { const [rawMachine, rawEnroll, rawDatetime, rawInout] = line.split(',').map((part) => part?.trim() ?? ''); const inout = rawInout === 'out' ? 'out' : rawInout === 'in' ? 'in' : 'unknown'; return { machine: rawMachine ?? '', enroll: rawEnroll ?? '', datetime: rawDatetime ?? '', inout }; }); }
function attendanceFingerprint(row: { machine: string; enroll: string; datetime: string; inout: string }) { return createHash('sha256').update(`${row.machine}|${row.enroll}|${row.datetime}|${row.inout}`).digest('hex'); }
function rowsOf(result: unknown): Array<Record<string, unknown>> { return Array.isArray(result) ? result as Array<Record<string, unknown>> : ((result as { rows?: Array<Record<string, unknown>> }).rows ?? []); }
function sumLines(values: string[]): string { return values.reduce((sum, valueText) => sum.plus(new Decimal(valueText)), new Decimal(0)).toFixed(4); }
function payslipHtml(yearMonth: string, employeeName: string, netValue: string) { return `<!doctype html><html dir="rtl"><body><h1>قسيمة راتب ${escapeHtml(yearMonth)}</h1><p>${escapeHtml(employeeName)}: ${escapeHtml(netValue)}</p></body></html>`; }
function escapeHtml(value: string) { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;'); }
