import { isNull } from 'drizzle-orm';
import { date, index, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

import { baseAuditColumns, baseLegacyColumns, baseSoftDeleteColumns } from '../columns.js';

import { warehouses } from './organization.js';
import { items } from './catalog.js';
import { tenants } from './platform.js';

const qty = { precision: 20, scale: 4, mode: 'string' as const };
const money = { precision: 20, scale: 4, mode: 'string' as const };

export const inventoryTransactions = pgTable('inventory_transactions', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  itemId: uuid('item_id').notNull().references(() => items.id, { onDelete: 'restrict' }), warehouseId: uuid('warehouse_id').notNull().references(() => warehouses.id, { onDelete: 'restrict' }),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(), docType: text('doc_type').notNull(), docId: uuid('doc_id').notNull(), lineId: uuid('line_id'), direction: text('direction').notNull(), qty: numeric('qty', qty).notNull(), baseQty: numeric('base_qty', qty).notNull(), unitCost: numeric('unit_cost', money).notNull(), totalCost: numeric('total_cost', money).notNull(), costing: text('costing').notNull(), lotId: uuid('lot_id'), serialId: uuid('serial_id'), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), createdBy: uuid('created_by'),
}, (t) => ({ scope: index('inventory_transactions_scope_idx').on(t.tenantId, t.itemId, t.warehouseId, t.occurredAt), document: uniqueIndex('inventory_transactions_document_line_key').on(t.tenantId, t.docType, t.docId, t.lineId), lot: index('inventory_transactions_lot_idx').on(t.tenantId, t.lotId), serial: index('inventory_transactions_serial_idx').on(t.tenantId, t.serialId) }));

export const stockBalances = pgTable('stock_balances', {
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), itemId: uuid('item_id').notNull().references(() => items.id, { onDelete: 'restrict' }), warehouseId: uuid('warehouse_id').notNull().references(() => warehouses.id, { onDelete: 'restrict' }), quantity: numeric('quantity', qty).notNull().default('0'), value: numeric('value', money).notNull().default('0'), averageCost: numeric('average_cost', money).notNull().default('0'), version: integer('version').notNull().default(1), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ pk: primaryKey({ columns: [t.tenantId, t.itemId, t.warehouseId] }), item: index('stock_balances_tenant_item_idx').on(t.tenantId, t.itemId), warehouse: index('stock_balances_tenant_warehouse_idx').on(t.tenantId, t.warehouseId) }));

export const stockAdjustments = pgTable('stock_adjustments', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), warehouseId: uuid('warehouse_id').notNull().references(() => warehouses.id), branchId: uuid('branch_id').notNull(), number: text('number').notNull(), status: text('status').notNull().default('draft'), reason: text('reason').notNull(), approvedAt: timestamp('approved_at', { withTimezone: true }), approvedBy: uuid('approved_by'), journalEntryId: uuid('journal_entry_id'), ...baseAuditColumns(), ...baseLegacyColumns() }, (t) => ({ number: uniqueIndex('stock_adjustments_tenant_number_key').on(t.tenantId, t.number), status: index('stock_adjustments_status_idx').on(t.tenantId, t.status) }));
export const stockAdjustmentLines = pgTable('stock_adjustment_lines', { adjustmentId: uuid('adjustment_id').notNull().references(() => stockAdjustments.id, { onDelete: 'cascade' }), lineNo: integer('line_no').notNull(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), itemId: uuid('item_id').notNull().references(() => items.id), expectedQty: numeric('expected_qty', qty).notNull(), countedQty: numeric('counted_qty', qty).notNull(), unitCost: numeric('unit_cost', money), lotId: uuid('lot_id'), note: text('note') }, (t) => ({ pk: primaryKey({ columns: [t.adjustmentId, t.lineNo] }), scope: index('stock_adjustment_lines_scope_idx').on(t.tenantId, t.itemId) }));

export const stockTransfers = pgTable('stock_transfers', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), fromWarehouseId: uuid('from_warehouse_id').notNull().references(() => warehouses.id), toWarehouseId: uuid('to_warehouse_id').notNull().references(() => warehouses.id), number: text('number').notNull(), status: text('status').notNull().default('draft'), sentAt: timestamp('sent_at', { withTimezone: true }), receivedAt: timestamp('received_at', { withTimezone: true }), cancelledAt: timestamp('cancelled_at', { withTimezone: true }), ...baseAuditColumns(), ...baseLegacyColumns() }, (t) => ({ number: uniqueIndex('stock_transfers_tenant_number_key').on(t.tenantId, t.number), status: index('stock_transfers_status_idx').on(t.tenantId, t.status) }));
export const stockTransferLines = pgTable('stock_transfer_lines', { transferId: uuid('transfer_id').notNull().references(() => stockTransfers.id, { onDelete: 'cascade' }), lineNo: integer('line_no').notNull(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), itemId: uuid('item_id').notNull().references(() => items.id), qty: numeric('qty', qty).notNull(), sentQty: numeric('sent_qty', qty).notNull().default('0'), receivedQty: numeric('received_qty', qty).notNull().default('0'), unitCost: numeric('unit_cost', money).notNull().default('0'), lotId: uuid('lot_id'), serialIds: jsonb('serial_ids').$type<string[]>().notNull().default([]) }, (t) => ({ pk: primaryKey({ columns: [t.transferId, t.lineNo] }), scope: index('stock_transfer_lines_scope_idx').on(t.tenantId, t.itemId) }));

export const itemLots = pgTable('item_lots', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), itemId: uuid('item_id').notNull().references(() => items.id), lotNo: text('lot_no').notNull(), expiryDate: date('expiry_date'), receivedAt: timestamp('received_at', { withTimezone: true }), ...baseAuditColumns(), ...baseSoftDeleteColumns() }, (t) => ({ lot: uniqueIndex('item_lots_tenant_item_lot_key').on(t.tenantId, t.itemId, t.lotNo).where(isNull(t.deletedAt)) }));
export const itemSerials = pgTable('item_serials', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), itemId: uuid('item_id').notNull().references(() => items.id), serialNo: text('serial_no').notNull(), lotId: uuid('lot_id'), status: text('status').notNull().default('available'), warehouseId: uuid('warehouse_id'), ...baseAuditColumns(), ...baseSoftDeleteColumns() }, (t) => ({ serial: uniqueIndex('item_serials_tenant_serial_key').on(t.tenantId, t.serialNo).where(isNull(t.deletedAt)), item: index('item_serials_stock_idx').on(t.tenantId, t.itemId, t.warehouseId, t.status) }));
export const invoiceItemAttributes = pgTable('invoice_item_attributes', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), documentType: text('document_type').notNull(), documentId: uuid('document_id').notNull(), lineId: uuid('line_id').notNull(), attributes: jsonb('attributes').$type<Record<string, unknown>>().notNull().default({}), ...baseAuditColumns() }, (t) => ({ line: uniqueIndex('invoice_item_attributes_line_key').on(t.tenantId, t.documentType, t.documentId, t.lineId) }));

export const inventoryTables = { inventoryTransactions, stockBalances, stockAdjustments, stockAdjustmentLines, stockTransfers, stockTransferLines, itemLots, itemSerials, invoiceItemAttributes };
export type InventoryTransaction = typeof inventoryTransactions.$inferSelect;
export type StockBalance = typeof stockBalances.$inferSelect;
export type StockTransfer = typeof stockTransfers.$inferSelect;
export type ItemLot = typeof itemLots.$inferSelect;
export type ItemSerial = typeof itemSerials.$inferSelect;
