import { sql } from 'drizzle-orm';
import { boolean, date, index, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

import { baseAuditColumns, baseLegacyColumns, baseSoftDeleteColumns } from '../columns.js';

import { items } from './catalog.js';
import { branches, warehouses } from './organization.js';
import { parties } from './parties.js';
import { salesInvoiceLines, salesInvoices } from './sales.js';
import { tenants } from './platform.js';

const money = { precision: 20, scale: 4, mode: 'string' as const };
const pct = { precision: 7, scale: 4, mode: 'string' as const };

export const opticalPrescriptions = pgTable('optical_prescriptions', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), partyId: uuid('party_id').notNull().references(() => parties.id), invoiceLineId: uuid('invoice_line_id').references(() => salesInvoiceLines.id, { onDelete: 'set null' }), orientation: text('orientation').notNull().default('distance'), rightEye: jsonb('right_eye').$type<{ sph?: string; cyl?: string; axis?: string; add?: string; ipd?: string }>().notNull().default({}), leftEye: jsonb('left_eye').$type<{ sph?: string; cyl?: string; axis?: string; add?: string; ipd?: string }>().notNull().default({}), otherGrid: jsonb('other_grid').$type<Record<string, string>>().notNull().default({}), notes: text('notes'), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns(),
}, (t) => ({ party: index('optical_prescriptions_party_idx').on(t.tenantId, t.partyId), line: index('optical_prescriptions_line_idx').on(t.tenantId, t.invoiceLineId) }));

export const customerMeasurements = pgTable('customer_measurements', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), partyId: uuid('party_id').notNull().references(() => parties.id), kind: text('kind').notNull().default('tailoring'), measurements: jsonb('measurements').$type<Record<string, string>>().notNull().default({}), notes: text('notes'), active: boolean('active').notNull().default(true), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns(),
}, (t) => ({ party: index('customer_measurements_party_idx').on(t.tenantId, t.partyId, t.createdAt) }));

export const vesselGroups = pgTable('vessel_groups', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), name: text('name').notNull(), code: text('code'), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns(),
}, (t) => ({ code: uniqueIndex('vessel_groups_code_key').on(t.tenantId, t.code).where(sql`code IS NOT NULL AND deleted_at IS NULL`) }));
export const vessels = pgTable('vessels', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), groupId: uuid('group_id').references(() => vesselGroups.id, { onDelete: 'set null' }), code: text('code').notNull(), name: text('name').notNull(), status: text('status').notNull().default('available'), capacity: integer('capacity').notNull().default(0), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns(),
}, (t) => ({ code: uniqueIndex('vessels_code_key').on(t.tenantId, t.code).where(sql`deleted_at IS NULL`), group: index('vessels_group_idx').on(t.tenantId, t.groupId) }));
export const vesselGroupPricing = pgTable('vessel_group_pricing', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), groupId: uuid('group_id').notNull().references(() => vesselGroups.id, { onDelete: 'cascade' }), periodKind: text('period_kind').notNull(), price: numeric('price', money).notNull(), currency: text('currency').notNull().default('SAR'), ...baseAuditColumns(),
}, (t) => ({ kind: uniqueIndex('vessel_group_pricing_kind_key').on(t.tenantId, t.groupId, t.periodKind) }));
export const vesselOwners = pgTable('vessel_owners', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), vesselId: uuid('vessel_id').notNull().references(() => vessels.id, { onDelete: 'cascade' }), partyId: uuid('party_id').notNull().references(() => parties.id), percent: numeric('percent', pct).notNull(), ...baseAuditColumns(), ...baseSoftDeleteColumns(),
}, (t) => ({ owner: uniqueIndex('vessel_owners_party_key').on(t.tenantId, t.vesselId, t.partyId).where(sql`deleted_at IS NULL`) }));
export const marinaBookings = pgTable('marina_bookings', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), branchId: uuid('branch_id').notNull().references(() => branches.id), partyId: uuid('party_id').notNull().references(() => parties.id), vesselId: uuid('vessel_id').notNull().references(() => vessels.id), startsAt: timestamp('starts_at', { withTimezone: true }).notNull(), endsAt: timestamp('ends_at', { withTimezone: true }).notNull(), companions: integer('companions').notNull().default(0), insuranceAmount: numeric('insurance_amount', money).notNull().default('0'), status: text('status').notNull().default('booked'), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns(),
}, (t) => ({ vesselTime: index('marina_bookings_vessel_time_idx').on(t.tenantId, t.vesselId, t.startsAt, t.endsAt) }));
export const marinaBookingAdditions = pgTable('marina_booking_additions', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), bookingId: uuid('booking_id').notNull().references(() => marinaBookings.id, { onDelete: 'cascade' }), description: text('description').notNull(), amount: numeric('amount', money).notNull(), ...baseAuditColumns(),
});
export const rentalInvoices = pgTable('rental_invoices', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), bookingId: uuid('booking_id').notNull().references(() => marinaBookings.id), salesInvoiceId: uuid('sales_invoice_id').references(() => salesInvoices.id, { onDelete: 'set null' }), periodAmount: numeric('period_amount', money).notNull(), additionsAmount: numeric('additions_amount', money).notNull().default('0'), insuranceAmount: numeric('insurance_amount', money).notNull().default('0'), total: numeric('total', money).notNull(), status: text('status').notNull().default('draft'), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}), ...baseAuditColumns(), ...baseLegacyColumns(),
}, (t) => ({ booking: uniqueIndex('rental_invoices_booking_key').on(t.tenantId, t.bookingId) }));
export const marinaViolations = pgTable('marina_violations', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), vesselId: uuid('vessel_id').references(() => vessels.id), bookingId: uuid('booking_id').references(() => marinaBookings.id), partyId: uuid('party_id').references(() => parties.id), violationDate: date('violation_date').notNull(), amount: numeric('amount', money).notNull().default('0'), description: text('description').notNull(), status: text('status').notNull().default('open'), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns(),
});
export const marinaOperationPlans = pgTable('marina_operation_plans', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), groupId: uuid('group_id').references(() => vesselGroups.id), planDate: date('plan_date').notNull(), name: text('name').notNull(), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns(),
}, (t) => ({ day: index('marina_operation_plans_day_idx').on(t.tenantId, t.planDate) }));
export const marinaOperationPlanLines = pgTable('marina_operation_plan_lines', {
  planId: uuid('plan_id').notNull().references(() => marinaOperationPlans.id, { onDelete: 'cascade' }), lineNo: integer('line_no').notNull(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), vesselId: uuid('vessel_id').notNull().references(() => vessels.id), periodLabel: text('period_label'), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
}, (t) => ({ pk: primaryKey({ columns: [t.planId, t.lineNo] }) }));

/** تحضير المراكب — one preparation per booking, plus the return that closes it. */
export const marinaPreparations = pgTable('marina_preparations', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), bookingId: uuid('booking_id').notNull().references(() => marinaBookings.id, { onDelete: 'cascade' }), vesselId: uuid('vessel_id').notNull().references(() => vessels.id), preparedOn: date('prepared_on').notNull(), status: text('status').notNull().default('prepared'), fuelLevel: text('fuel_level'), lifeJackets: integer('life_jackets').notNull().default(0), checklist: jsonb('checklist').$type<Record<string, unknown>>().notNull().default({}), notes: text('notes'), preparedAt: timestamp('prepared_at', { withTimezone: true }).notNull().defaultNow(), returnedAt: timestamp('returned_at', { withTimezone: true }), returnNotes: text('return_notes'), ...baseAuditColumns(),
}, (t) => ({ booking: uniqueIndex('marina_preparations_booking_key').on(t.tenantId, t.bookingId), day: index('marina_preparations_day_idx').on(t.tenantId, t.preparedOn, t.status) }));

/** إغلاق اليومية — a closed harbour day refuses new bookings and rental invoices. */
export const marinaDayClosings = pgTable('marina_day_closings', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), branchId: uuid('branch_id').notNull().references(() => branches.id), closeDate: date('close_date').notNull(), bookingsCount: integer('bookings_count').notNull().default(0), rentalsCount: integer('rentals_count').notNull().default(0), rentalsTotal: numeric('rentals_total', money).notNull().default('0'), additionsTotal: numeric('additions_total', money).notNull().default('0'), insuranceTotal: numeric('insurance_total', money).notNull().default('0'), violationsTotal: numeric('violations_total', money).notNull().default('0'), notes: text('notes'), closedAt: timestamp('closed_at', { withTimezone: true }).notNull().defaultNow(), closedBy: uuid('closed_by'), ...baseAuditColumns(),
}, (t) => ({ day: uniqueIndex('marina_day_closings_day_key').on(t.tenantId, t.branchId, t.closeDate) }));

export const vehicleMakes = pgTable('vehicle_makes', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), name: text('name').notNull(), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns() }, (t) => ({ name: uniqueIndex('vehicle_makes_name_key').on(t.tenantId, t.name).where(sql`deleted_at IS NULL`) }));
export const vehicleModels = pgTable('vehicle_models', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), makeId: uuid('make_id').notNull().references(() => vehicleMakes.id, { onDelete: 'cascade' }), name: text('name').notNull(), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns() }, (t) => ({ name: uniqueIndex('vehicle_models_name_key').on(t.tenantId, t.makeId, t.name).where(sql`deleted_at IS NULL`) }));
export const itemVehicleFitment = pgTable('item_vehicle_fitment', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), itemId: uuid('item_id').notNull().references(() => items.id, { onDelete: 'cascade' }), makeId: uuid('make_id').notNull().references(() => vehicleMakes.id), modelId: uuid('model_id').references(() => vehicleModels.id), yearFrom: integer('year_from'), yearTo: integer('year_to'), notes: text('notes'), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns() }, (t) => ({ lookup: index('item_vehicle_fitment_lookup_idx').on(t.tenantId, t.makeId, t.modelId, t.yearFrom, t.yearTo), item: index('item_vehicle_fitment_item_idx').on(t.tenantId, t.itemId) }));

export const sallaConnections = pgTable('salla_connections', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), storeId: text('store_id').notNull(), accessTokenEnc: text('access_token_enc').notNull(), refreshTokenEnc: text('refresh_token_enc'), webhookSecretEnc: text('webhook_secret_enc').notNull(), status: text('status').notNull().default('active'), scopes: jsonb('scopes').$type<string[]>().notNull().default([]), expiresAt: timestamp('expires_at', { withTimezone: true }), ...baseAuditColumns(), ...baseSoftDeleteColumns() }, (t) => ({ store: uniqueIndex('salla_connections_store_key').on(t.tenantId, t.storeId).where(sql`deleted_at IS NULL`) }));
export const sallaItemSync = pgTable('salla_item_sync', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), connectionId: uuid('connection_id').references(() => sallaConnections.id, { onDelete: 'cascade' }), itemId: uuid('item_id').notNull().references(() => items.id, { onDelete: 'cascade' }), remoteId: text('remote_id'), lastExportedSnapshot: jsonb('last_exported_snapshot').$type<Record<string, unknown>>().notNull().default({}), diffFlags: jsonb('diff_flags').$type<string[]>().notNull().default([]), status: text('status').notNull().default('pending'), nextRetryAt: timestamp('next_retry_at', { withTimezone: true }), attempts: integer('attempts').notNull().default(0), ...baseAuditColumns() }, (t) => ({ item: uniqueIndex('salla_item_sync_item_key').on(t.tenantId, t.connectionId, t.itemId) }));
export const sallaExportLog = pgTable('salla_export_log', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), connectionId: uuid('connection_id').references(() => sallaConnections.id, { onDelete: 'set null' }), itemId: uuid('item_id').references(() => items.id, { onDelete: 'set null' }), action: text('action').notNull(), status: text('status').notNull().default('queued'), requestPayload: jsonb('request_payload').$type<Record<string, unknown>>().notNull().default({}), responsePayload: jsonb('response_payload').$type<Record<string, unknown>>(), error: text('error'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (t) => ({ status: index('salla_export_log_status_idx').on(t.tenantId, t.status) }));
export const sallaBranchMappings = pgTable('salla_branch_mappings', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), connectionId: uuid('connection_id').references(() => sallaConnections.id, { onDelete: 'cascade' }), branchId: uuid('branch_id').references(() => branches.id), warehouseId: uuid('warehouse_id').references(() => warehouses.id), cashLocationId: uuid('cash_location_id'), remoteBranchId: text('remote_branch_id'), ...baseAuditColumns(), ...baseSoftDeleteColumns() }, (t) => ({ remote: uniqueIndex('salla_branch_mappings_remote_key').on(t.tenantId, t.connectionId, t.remoteBranchId).where(sql`deleted_at IS NULL`) }));

export const nicheTables = { opticalPrescriptions, customerMeasurements, vesselGroups, vessels, vesselGroupPricing, vesselOwners, marinaBookings, marinaBookingAdditions, rentalInvoices, marinaViolations, marinaOperationPlans, marinaOperationPlanLines, marinaPreparations, marinaDayClosings, vehicleMakes, vehicleModels, itemVehicleFitment, sallaConnections, sallaItemSync, sallaExportLog, sallaBranchMappings };
