import { sql } from 'drizzle-orm';
import { date, index, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

import { baseAuditColumns, baseLegacyColumns, baseSoftDeleteColumns } from '../columns.js';

import { accounts, costCenters, journalEntries, fiscalPeriods } from './accounting.js';
import { branches, cashLocations } from './organization.js';
import { parties } from './parties.js';
import { tenants } from './platform.js';

const money = { precision: 20, scale: 4, mode: 'string' as const };

export const vouchers = pgTable('vouchers', {
  id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), branchId: uuid('branch_id').notNull().references(() => branches.id),
  kind: text('kind').notNull(), subtype: text('subtype').notNull(), number: text('number'), date: date('date').notNull(), partyId: uuid('party_id').references(() => parties.id), counterAccountId: uuid('counter_account_id').references(() => accounts.id), cashLocationId: uuid('cash_location_id').notNull().references(() => cashLocations.id), method: text('method').notNull(), amount: numeric('amount', money).notNull(), vatAmount: numeric('vat_amount', money).notNull().default('0'), netAmount: numeric('net_amount', money).notNull().default('0'), currency: text('currency').notNull().default('SAR'), fxRate: numeric('fx_rate', { precision: 20, scale: 10 }), chequeNo: text('cheque_no'), chequeDate: date('cheque_date'), bankName: text('bank_name'), chequeState: text('cheque_state'), costCenterId: uuid('cost_center_id').references(() => costCenters.id), referenceNo: text('reference_no'), referenceDate: date('reference_date'), recipient: text('recipient'), status: text('status').notNull().default('draft'), journalEntryId: uuid('journal_entry_id').references(() => journalEntries.id), fiscalPeriodId: uuid('fiscal_period_id').references(() => fiscalPeriods.id), postedAt: timestamp('posted_at', { withTimezone: true }), voidedAt: timestamp('voided_at', { withTimezone: true }), idempotencyKey: text('idempotency_key'), ...baseAuditColumns(), ...baseLegacyColumns(),
}, (t) => ({ number: uniqueIndex('vouchers_tenant_number_key').on(t.tenantId, t.number).where(sql`number IS NOT NULL`), idem: uniqueIndex('vouchers_tenant_idempotency_key').on(t.tenantId, t.idempotencyKey).where(sql`idempotency_key IS NOT NULL`), scope: index('vouchers_scope_idx').on(t.tenantId, t.branchId, t.status, t.kind), cash: index('vouchers_cash_idx').on(t.tenantId, t.cashLocationId, t.postedAt) }));

export const cashTransfers = pgTable('cash_transfers', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), branchId: uuid('branch_id').notNull().references(() => branches.id), fromCashLocationId: uuid('from_cash_location_id').notNull().references(() => cashLocations.id), toCashLocationId: uuid('to_cash_location_id').notNull().references(() => cashLocations.id), number: text('number'), amount: numeric('amount', money).notNull(), currency: text('currency').notNull().default('SAR'), status: text('status').notNull().default('draft'), sentJournalEntryId: uuid('sent_journal_entry_id').references(() => journalEntries.id), receivedJournalEntryId: uuid('received_journal_entry_id').references(() => journalEntries.id), sentAt: timestamp('sent_at', { withTimezone: true }), receivedAt: timestamp('received_at', { withTimezone: true }), ...baseAuditColumns(), ...baseLegacyColumns() }, (t) => ({ number: uniqueIndex('cash_transfers_tenant_number_key').on(t.tenantId, t.number).where(sql`number IS NOT NULL`), scope: index('cash_transfers_scope_idx').on(t.tenantId, t.status) }));

export const expenseTypes = pgTable('expense_types', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), nameAr: text('name_ar').notNull(), nameEn: text('name_en'), accountId: uuid('account_id').notNull().references(() => accounts.id), costCenterId: uuid('cost_center_id').references(() => costCenters.id), ...baseAuditColumns(), ...baseSoftDeleteColumns(), ...baseLegacyColumns() }, (t) => ({ name: uniqueIndex('expense_types_tenant_name_key').on(t.tenantId, t.nameAr).where(sql`deleted_at IS NULL`) }));

export const shiftCloses = pgTable('shift_closes', { id: uuid('id').primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), branchId: uuid('branch_id').notNull().references(() => branches.id), userId: uuid('user_id').notNull(), openedAt: timestamp('opened_at', { withTimezone: true }).notNull().defaultNow(), closedAt: timestamp('closed_at', { withTimezone: true }), status: text('status').notNull().default('open'), expectedCash: numeric('expected_cash', money).notNull().default('0'), countedCash: numeric('counted_cash', money).notNull().default('0'), diff: numeric('diff', money).notNull().default('0'), summary: jsonb('summary').$type<Record<string, unknown>>().notNull().default({}), reportHtml: text('report_html'), journalEntryId: uuid('journal_entry_id').references(() => journalEntries.id, { onDelete: 'restrict' }), ...baseAuditColumns() }, (t) => ({ open: uniqueIndex('shift_closes_one_open_key').on(t.tenantId, t.branchId, t.userId).where(sql`status = 'open'`), scope: index('shift_closes_scope_idx').on(t.tenantId, t.branchId, t.status), journal: index('shift_closes_journal_idx').on(t.tenantId, t.journalEntryId).where(sql`journal_entry_id IS NOT NULL`) }));

export const shiftCloseLines = pgTable('shift_close_lines', { shiftCloseId: uuid('shift_close_id').notNull().references(() => shiftCloses.id, { onDelete: 'cascade' }), lineNo: integer('line_no').notNull(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), kind: text('kind').notNull(), method: text('method'), partyId: uuid('party_id').references(() => parties.id), amount: numeric('amount', money).notNull().default('0'), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}) }, (t) => ({ pk: primaryKey({ columns: [t.shiftCloseId, t.lineNo] }) }));

export const cashCountLines = pgTable('cash_count_lines', { shiftCloseId: uuid('shift_close_id').notNull().references(() => shiftCloses.id, { onDelete: 'cascade' }), lineNo: integer('line_no').notNull(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }), currencyCode: text('currency_code').notNull().default('SAR'), denomination: numeric('denomination', money).notNull(), count: integer('count').notNull(), total: numeric('total', money).notNull() }, (t) => ({ pk: primaryKey({ columns: [t.shiftCloseId, t.lineNo] }) }));

export const treasuryTables = { vouchers, cashTransfers, expenseTypes, shiftCloses, shiftCloseLines, cashCountLines };
export type Voucher = typeof vouchers.$inferSelect;
export type CashTransfer = typeof cashTransfers.$inferSelect;
export type ShiftClose = typeof shiftCloses.$inferSelect;
