namespace SmartAuditERP
{

	public class StoredQueries
	{
		public static string InsertInv = "insert into Inv(InvGlobalID,proc_type,id,date,inv_type,OrderType,safe,stock,cust_id,sales_emp,InvTotal,AdditionsTot,Insurance,tot_net,paid,minus,EntryID,Reff_No,Reff_date,branch,IS_Buy,IS_Deleted,salesman,tax,pay_type,bank,cash,visa,notes,InvProfit,Sync,ExtraVAT,AdditionalCost,InvoiceStatus,PriceIncVAT,PaymentStatus,InvCombinedId,ItemsDiscount,InvCost,FreeVATSales,InvSum,VATPercent,CurrencyCode,CloudID,CashCustomerName,CashCustomerMobile,QRCode,InvoiceHash,UUID,ZatcaSent,TotalWithholdingTax,TableNo,Balance_previews)values(@InvGlobalID,@proc_type,@id,@date,@inv_type,@OrderType,@safe,@stock,@cust_id,@sales_emp,@InvTotal,@AdditionsTot,@Insurance,@tot_net,@paid,@minus,@EntryID,@Reff_No,@Reff_date,@branch,@IS_Buy,@IS_Deleted,@salesman,@tax,@pay_type,@bank,@cash,@visa,@notes,@InvProfit,@Sync,@ExtraVAT,@AdditionalCost,@InvoiceStatus,@PriceIncVAT,@PaymentStatus,@InvCombinedId,@ItemsDiscount,@InvCost,@FreeVATSales,@InvSum,@VATPercent,@CurrencyCode,@CloudID,@CashCustomerName,@CashCustomerMobile,@QRCode,@InvoiceHash,@UUID,@ZatcaSent,@TotalWithholdingTax,@TableNo,@Balance_previews)";

		public static string UpdateInv = " update Inv set id=@id ,proc_type=@proc_type, date=@date ,inv_type=@inv_type ,OrderType=@OrderType,safe=@safe ,stock=@stock ,\r\n                              cust_id=@cust_id ,sales_emp=@sales_emp ,InvTotal=@InvTotal ,AdditionsTot=@AdditionsTot,Insurance=@Insurance,tot_net=@tot_net,minus=@minus,Reff_No=@Reff_No,Reff_date=@Reff_date, IS_Deleted=@IS_Deleted,salesman=@salesman, tax=@tax, pay_type=@pay_type, bank=@bank ,cash=@cash,visa=@visa,notes=@notes,InvProfit=@InvProfit,Sync=@Sync,paid=@paid\r\n                                              ,EntryID=@EntryID,ExtraVAT=@ExtraVAT,AdditionalCost=@AdditionalCost,InvoiceStatus=@InvoiceStatus ,PriceIncVAT=@PriceIncVAT,PaymentStatus=@PaymentStatus,InvCombinedId=@InvCombinedId,ItemsDiscount=@ItemsDiscount,InvCost=@InvCost,FreeVATSales=@FreeVATSales,InvSum=@InvSum,VATPercent=@VATPercent,CurrencyCode=@CurrencyCode,CloudID=@CloudID,CashCustomerName=@CashCustomerName,CashCustomerMobile=@CashCustomerMobile,TotalWithholdingTax=@TotalWithholdingTax,TableNo=@TableNo,Balance_previews=@Balance_previews where  InvGlobalID=@InvGlobalID";

		public static string InsertInvSub = "insert into Inv_Sub(InvGlobalID,proc_id,proc_type,ItemId,unit,val,val1,exchange_price,expire_date,taxperc,taxval,discount,Store,UnitEquality,[Description],ProductId,AvrgCost,CurrentQnty,notes,ItemAddedCost,ItemPriceWithoutVAT,WithholdingTax,WithholdingTaxPerc,ItemCostCenter,ItemAdditionalTax,ItemAdditionalTaxPerc) \r\n                                            values(@InvGlobalID,@proc_id,@proc_type,@ItemId,@unit,@val,@val1,@exchange_price,@expire_date,@taxperc,@taxval,@discount,@Store,@UnitEquality,@Description,@ProductId,@AvrgCost,@CurrentQnty,@notes,@ItemAddedCost,@ItemPriceWithoutVAT,@WithholdingTax,@WithholdingTaxPerc,@ItemCostCenter,@ItemAdditionalTax,@ItemAdditionalTaxPerc)";

		public static string InsertInvRent = " insert into RentInvoice(proc_type,id,date,stock,MarineId,GroupId,cust_id,sales_emp,tot_Rent,tot_Additions,Insurance,tot_net,RentPeriod,paid,Discount,Restraction_id,branch,IS_Deleted,tax,pay_type,bank,cash,visa,note,Companions,Reff_No,Reff_date)values\r\n                                              (@proc_type,@id,@date,@stock,@MarineId,@GroupId,@cust_id,@sales_emp,@tot_Rent,@tot_Additions,@Insurance,@tot_net,@RentPeriod,@paid,@Discount,@Restraction_id,@branch,@IS_Deleted,@tax,@pay_type,@bank,@cash,@visa,@note,@Companions,@Reff_No,@Reff_date)";

		public static string UpdateInvRent = "update RentInvoice set proc_type=@proc_type, date=@date ,stock=@stock ,MarineId=@MarineId,GroupId=@GroupId,\r\n                                         cust_id=@cust_id ,sales_emp=@sales_emp, tot_Rent=@tot_Rent ,tot_Additions=@tot_Additions ,Insurance=@Insurance,tot_net=@tot_net,RentPeriod=@RentPeriod,Discount=@Discount,Restraction_id=@Restraction_id, IS_Deleted=@IS_Deleted, tax=@tax, pay_type=@pay_type, bank=@bank ,cash=@cash,visa=@visa,note=@note\r\n                                               where proc_id=@proc_id";

		public static string InsertEntry = "insert into Entry(GlobalID,id,Date,doc_no,type,state,notes,branch,IS_Deleted,EmpID,Sync,IsVAT)values(@GlobalID,@id,@Date,@doc_no,@type,@state,@notes,@branch,@IS_Deleted,@EmpID,@Sync,@IsVAT)";

		public static string UpdateEntry = "Update Entry set Date=@Date,state=@state ,notes=@notes,IS_Deleted=@IS_Deleted,EmpID=@EmpID,Sync=@Sync,IsVAT=@IsVAT where  GlobalID=@GlobalID";

		public static string InsertEntrySub = "insert into Entry_sub(EntryGlobalID,res_id,dept,credit,acc_no,notes,branch,CCcode,salesman)values(@EntryGlobalID,@res_id,@dept,@credit,@acc_no,@notes,@branch,@CCcode,@salesman)";

		public static string InsertContractInv = "insert into PM_ContractInv( ContrNo,ContrType,ProcType,statusPk,BankId,PayType,\r\n\tTreasuryPk,\r\n\tPayerName,\r\n\tClientPk,\r\n\tEmpNo,\r\n\tBranchPk,\r\n\tSalesman,\r\n\tRestractionPk,\r\n\tRegsDate,\r\n    RefrNo ,\r\n\tExcutePeriod,\r\n\tStartDate,\r\n\tEndDate,\r\n\tTotVal,\r\n\tVATval,\r\n\tdiscount,\r\n\tNetCost,\r\n\tIS_Deleted )\r\n\tvalues( \r\n\t@ContrNo,\r\n\t@ContrType,\r\n\t@ProcType,\r\n\t@statusPk,\r\n\t@BankId,\r\n\t@PayType,\r\n\t@TreasuryPk,\r\n\t@PayerName,\r\n\t@ClientPk,\r\n\t@EmpNo,\r\n\t@BranchPk,\r\n\t@Salesman,\r\n\t@RestractionPk,\r\n\t@RegsDate,\r\n\t@RefrNo ,\r\n\t@ExcutePeriod,\r\n\t@StartDate,\r\n\t@EndDate,\r\n\t@TotVal,\r\n\t@VATval,\r\n\t@discount,\r\n\t@NetCost,\r\n\t@IS_Deleted  ) ";

		public static string UpdateContractInv = "update PM_ContractInv set \r\n   ContrNo=@ContrNo,\r\n   ContrType=@ContrType,\r\n\tProcType=@ProcType,\r\n\tstatusPk=@statusPk,\r\n\tBankId=@BankId,\r\n\tPayType=@PayType,\r\n\tTreasuryPk=@TreasuryPk,\r\n\tPayerName=@PayerName,\r\n\tClientPk=@ClientPk,\r\n\tEmpNo=@EmpNo,\r\n\tBranchPk=@BranchPk,\r\n\tSalesman=@Salesman,\r\n\tRestractionPk=@RestractionPk,\r\n\tRegsDate=@RegsDate,\r\n\tRefrNo=@RefrNo,\r\n\tExcutePeriod=@ExcutePeriod,\r\n\tStartDate=@StartDate,\r\n\tEndDate=@EndDate,\r\n\tTotVal=@TotVal,\r\n\tVATval=@VATval,\r\n\tdiscount=@discount,\r\n\tNetCost=@NetCost,\r\n\tIS_Deleted=@IS_Deleted where Contr_id=@Contr_id";

		public static string UpdateItemCost = "  update Inv_sub set CurrentQnty=@CurrentQnty, AvrgCost=@AvrgCost  where InvGlobalID=@InvGlobalID and ItemId=@ItemId";

		public static string UpdateInvProfit = "  update Inv set InvProfit=@InvProfit where InvGlobalID=@InvGlobalID ";

		public static string InsertReceipt = "INSERT INTO [dbo].[Receipts] (\r\nGlobalID\r\n,ReceiptNo\r\n,ReceiptDate\r\n,EmpId\r\n,ClientID\r\n,CreditAcc\r\n,DebitAcc\r\n,Payment\r\n,VAT\r\n,NetVal\r\n,ReceiptType\r\n,PaymentType\r\n,BankId\r\n,TreasuryID\r\n,SalesManID\r\n,CheckNo\r\n,CheckDate\r\n,Checkbank\r\n,CheckState\r\n,State\r\n,Notes\r\n,EntryGlobalID\r\n,BranchID\r\n,ISDeleted\r\n,Cccode\r\n,ReffNo\r\n,Reffdate\r\n,Sync\r\n,Recipient)\r\nVALUES\r\n(@GlobalID\r\n,@ReceiptNo\r\n,@ReceiptDate\r\n,@EmpId\r\n,@ClientID\r\n,@CreditAcc\r\n,@DebitAcc\r\n,@Payment\r\n,@VAT\r\n,@NetVal\r\n,@ReceiptType\r\n,@PaymentType\r\n,@BankId\r\n,@TreasuryID\r\n,@SalesManID\r\n,@CheckNo\r\n,@CheckDate\r\n,@Checkbank\r\n,@CheckState\r\n,@State\r\n,@Notes\r\n,@EntryGlobalID\r\n,@BranchID\r\n,@ISDeleted\r\n,@Cccode\r\n,@ReffNo\r\n,@Reffdate\r\n,@Sync\r\n,@Recipient)";

		public static string UpdateReceipt = "Update   [dbo].[Receipts] set\r\nReceiptDate=@ReceiptDate\r\n,EmpId=@EmpId\r\n,ClientID=@ClientID\r\n,CreditAcc=@CreditAcc\r\n,DebitAcc=@DebitAcc\r\n,Payment=@Payment\r\n,VAT=@VAT\r\n,NetVal=@NetVal\r\n,ReceiptType=@ReceiptType\r\n,PaymentType=@PaymentType\r\n,BankId=@BankId\r\n,TreasuryID=@TreasuryID\r\n,SalesManID=@SalesManID\r\n,CheckNo=@CheckNo\r\n,CheckDate=@CheckDate\r\n,Checkbank=@Checkbank\r\n,CheckState=@CheckState\r\n,State=@State\r\n,Notes=@Notes\r\n,EntryGlobalID=@EntryGlobalID\r\n,ISDeleted=@ISDeleted\r\n,Cccode=@Cccode\r\n,ReffNo=@ReffNo\r\n,Reffdate=@Reffdate\r\n,Sync=@Sync\r\n,Recipient=@Recipient where GlobalID=@GlobalID";

		public static string InsertItem = "insert into Items(id,Code,GrpCode,name,nameEN,barcode,group_id,unit,purch_price,sale_price,limit,discount,tax_group,tax,IS_Deleted,image,ShowInPOS,Wscale,store,ItemType,ItemProperty,FillValue,MaxQtyLimit,EgyItemCode,WithholdingTax,EgyCodeType,MaxDicountParcent,MaxDiscountAmount,showInAndroid,CreatedDate,CreatedBy)values(@id,@Code,@GrpCode,@name,@nameEN,@barcode,@group_id,@unit,@purch_price,@sale_price,@limit,@discount,@tax_group,@tax,@IS_Deleted,@image,@ShowInPOS,@Wscale,@store,@ItemType,@ItemProperty,@FillValue,@MaxQtyLimit,@EgyItemCode,@WithholdingTax,@EgyCodeType,@MaxDicountParcent,@MaxDiscountAmount,@showInAndroid,@CreatedDate,@CreatedBy)";

		public static string UpdateItem = "update Items set Code=@Code,GrpCode=@GrpCode, name=@name,nameEN=@nameEN,barcode=@barcode,group_id=@group_id,unit=@unit,purch_price=@purch_price,sale_price=@sale_price,limit=@limit,discount=@discount,tax_group=@tax_group,tax=@tax,IS_Deleted=@IS_Deleted  , image = @image,ShowInPOS=@ShowInPOS,Wscale=@Wscale,store=@store,ItemType=@ItemType,ItemProperty=@ItemProperty,FillValue=@FillValue,MaxQtyLimit=@MaxQtyLimit,EgyItemCode=@EgyItemCode,WithholdingTax= @WithholdingTax,EgyCodeType=@EgyCodeType,\r\n                                        MaxDicountParcent=@MaxDicountParcent,MaxDiscountAmount=@MaxDiscountAmount ,showInAndroid=@showInAndroid,updatedDate=@updatedDate,updatedBy=@updatedBy  where id=@id";

		public static string CreateVersionTb = "IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES\r\nWHERE TABLE_NAME='DbVersions')\r\nBEGIN \r\nCREATE TABLE [dbo].[DbVersions](\r\n\t[VersionNo] [int] NOT NULL,\r\n\t[Versiontxt] [nvarchar](20) NULL,\r\n\t[Description] [nvarchar](max) NULL,\r\n\t[VersionType] [nvarchar](50) NULL,\r\n\t[PublishDate] [nvarchar](50) NULL,\r\n\t[UpdateDate] datetime NULL\r\n\t\t) ON [PRIMARY]\r\n    END";

		public static string InsertVersionInfo = "INSERT INTO [dbo].[DbVersions]([VersionNo],[Versiontxt],[Description] ,[VersionType],[PublishDate],[UpdateDate])VALUES(@VersionNo,@Versiontxt,@Description ,@VersionType,@PublishDate,@UpdateDate)";

		public static string CreateGediaSettingTb = "IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='GediaSetting')\r\nBEGIN \r\nCREATE TABLE [master].[dbo].[GediaSetting](\r\n\t[id] [int] IDENTITY(1,1) NOT NULL,\r\n\t[IsGediaActive] [bit] NULL,\r\n\t[GediaPort] [int] NULL,\r\n\t[GediaEnableReceiptPrint] [bit] NULL,\r\n CONSTRAINT [PK_GediaSetting] PRIMARY KEY CLUSTERED \r\n(\r\n\t[id] ASC\r\n)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\r\n) ON [PRIMARY]\r\n    END";

		public static string InsertGediaSettingTb = "IF NOT EXISTS(select id from GediaSetting where id=1)\r\nBEGIN\r\nSET IDENTITY_INSERT [dbo].[GediaSetting] ON \r\nINSERT [dbo].[GediaSetting] ([id], [IsGediaActive], [GediaPort],[GediaEnableReceiptPrint]) VALUES (1, 0, 0,1)\r\nSET IDENTITY_INSERT [dbo].[GediaSetting] OFF\r\nEND\r\n";

		public static string InsertInvcontract = "insert into InvContratct(InvGlobalID,proc_type,id,date,inv_type,safe,stock,cust_id,sales_emp,InvTotal,AdditionsTot,Insurance,tot_net,paid,minus,EntryID,Reff_No,Reff_date,branch,IS_Buy,IS_Deleted,salesman,tax,pay_type,bank,cash,visa,notes,InvProfit,Sync,ExtraVAT,AdditionalCost,InvoiceStatus,PriceIncVAT,PaymentStatus,InvCombinedId,ItemsDiscount,InvCost,FreeVATSales,InvSum,VATPercent,CurrencyCode,CloudID,CashCustomerName,CashCustomerMobile,QRCode,InvoiceHash,UUID,ZatcaSent,TotalWithholdingTax,TableNo,Balance_previews    \r\n      ,contract_total_value\r\n      ,original_work_amount\r\n      ,special_discount\r\n      ,amount_after_discount\r\n      ,vat_amount\r\n      ,total_with_vat\r\n      ,work_guarantee\r\n      ,net_due_this_payment\r\n      ,previously_paid_amount\r\n      ,remaining_contract_balance)values(@InvGlobalID,@proc_type,@id,@date,@inv_type,@safe,@stock,@cust_id,@sales_emp,@InvTotal,@AdditionsTot,@Insurance,@tot_net,@paid,@minus,@EntryID,@Reff_No,@Reff_date,@branch,@IS_Buy,@IS_Deleted,@salesman,@tax,@pay_type,@bank,@cash,@visa,@notes,@InvProfit,@Sync,@ExtraVAT,@AdditionalCost,@InvoiceStatus,@PriceIncVAT,@PaymentStatus,@InvCombinedId,@ItemsDiscount,@InvCost,@FreeVATSales,@InvSum,@VATPercent,@CurrencyCode,@CloudID,@CashCustomerName,@CashCustomerMobile,@QRCode,@InvoiceHash,@UUID,@ZatcaSent,@TotalWithholdingTax,@TableNo,@Balance_previews\r\n      ,@contract_total_value      \r\n      ,@original_work_amount\r\n      ,@special_discount\r\n      ,@amount_after_discount\r\n      ,@vat_amount\r\n      ,@total_with_vat\r\n      ,@work_guarantee\r\n      ,@net_due_this_payment\r\n      ,@previously_paid_amount\r\n      ,@remaining_contract_balance)";

		public static string UpdateInvcontract = " UPDATE InvContratct\r\nSET\r\n    id                      = @id,\r\n    proc_type               = @proc_type,\r\n    [date]                  = @date,\r\n    inv_type                = @inv_type,\r\n    safe                    = @safe,\r\n    stock                   = @stock,\r\n    cust_id                 = @cust_id,\r\n    sales_emp               = @sales_emp,\r\n    InvTotal                = @InvTotal,\r\n    AdditionsTot            = @AdditionsTot,\r\n    Insurance               = @Insurance,\r\n    tot_net                 = @tot_net,\r\n    minus                   = @minus,\r\n    Reff_No                 = @Reff_No,\r\n    Reff_date               = @Reff_date,\r\n    IS_Deleted              = @IS_Deleted,\r\n    salesman                = @salesman,\r\n    tax                     = @tax,\r\n    pay_type                = @pay_type,\r\n    bank                    = @bank,\r\n    cash                    = @cash,\r\n    visa                    = @visa,\r\n    notes                   = @notes,\r\n    InvProfit               = @InvProfit,\r\n    Sync                    = @Sync,\r\n    paid                    = @paid,\r\n    EntryID                 = @EntryID,\r\n    ExtraVAT                = @ExtraVAT,\r\n    AdditionalCost          = @AdditionalCost,\r\n    InvoiceStatus           = @InvoiceStatus,\r\n    PriceIncVAT             = @PriceIncVAT,\r\n    PaymentStatus           = @PaymentStatus,\r\n    InvCombinedId           = @InvCombinedId,\r\n    ItemsDiscount           = @ItemsDiscount,\r\n    InvCost                 = @InvCost,\r\n    FreeVATSales            = @FreeVATSales,\r\n    InvSum                  = @InvSum,\r\n    VATPercent              = @VATPercent,\r\n    CurrencyCode            = @CurrencyCode,\r\n    CloudID                 = @CloudID,\r\n    CashCustomerName        = @CashCustomerName,\r\n    CashCustomerMobile      = @CashCustomerMobile,\r\n    TotalWithholdingTax     = @TotalWithholdingTax,\r\n    TableNo                 = @TableNo,\r\n    Balance_previews        = @Balance_previews,\r\n    contract_total_value        = @contract_total_value,\r\n    original_work_amount        = @original_work_amount,\r\n    special_discount            = @special_discount,\r\n    amount_after_discount       = @amount_after_discount,\r\n    vat_amount                  = @vat_amount,\r\n    total_with_vat              = @total_with_vat,\r\n    work_guarantee              = @work_guarantee,\r\n    net_due_this_payment        = @net_due_this_payment,\r\n    previously_paid_amount      = @previously_paid_amount,\r\n    remaining_contract_balance  = @remaining_contract_balance\r\nWHERE\r\n    InvGlobalID = @InvGlobalID;\r\n";

		public static string InsertInvSubcontract = "insert into InvContratct_Sub(InvGlobalID,proc_id,proc_type,ItemId,unit,val,val1,exchange_price,expire_date,taxperc,taxval,discount,Store,UnitEquality,[Description],ProductId,AvrgCost,CurrentQnty,notes,ItemAddedCost,ItemPriceWithoutVAT,WithholdingTax,WithholdingTaxPerc,ItemCostCenter,ItemAdditionalTax,ItemAdditionalTaxPerc) \r\n                                            values(@InvGlobalID,@proc_id,@proc_type,@ItemId,@unit,@val,@val1,@exchange_price,@expire_date,@taxperc,@taxval,@discount,@Store,@UnitEquality,@Description,@ProductId,@AvrgCost,@CurrentQnty,@notes,@ItemAddedCost,@ItemPriceWithoutVAT,@WithholdingTax,@WithholdingTaxPerc,@ItemCostCenter,@ItemAdditionalTax,@ItemAdditionalTaxPerc)";
	}
}