import { Body, Controller, Get, Headers, Param, Post, Query, Req } from '@nestjs/common';
import type { Request } from 'express';

import { getTenantContext } from '../../platform/context/tenant-context.js';
import { RequiresPermission } from '../../platform/decorators/requires-permission.decorator.js';

import { SallaService } from './salla.service.js';
@Controller('integrations/salla')
export class SallaController { constructor(private readonly salla: SallaService) {} @Get('oauth/authorize') @RequiresPermission('salla.integration.manage') auth(@Query('clientId') clientId: string, @Query('redirectUri') redirectUri: string, @Query('state') state: string) { return this.salla.authUrl(getTenantContext().tenantId, { clientId, redirectUri, state }); } @Post('connections') @RequiresPermission('salla.integration.manage') connect(@Body() b: { storeId: string; accessToken: string; refreshToken?: string; webhookSecret: string; scopes?: string[]; expiresAt?: string }) { return this.salla.connect(getTenantContext().tenantId, b); } @Post('branch-mappings') @RequiresPermission('salla.integration.manage') map(@Body() b: { connectionId: string; branchId?: string; warehouseId?: string; cashLocationId?: string; remoteBranchId?: string }) { return this.salla.mapBranch(getTenantContext().tenantId, b); } @Post('export-queue') @RequiresPermission('salla.integration.manage') queue(@Body() b: { connectionId: string; itemId: string; action?: 'create' | 'update' | 'price' | 'qty' }) { return this.salla.queueExport(getTenantContext().tenantId, b); } @Post('export-next') @RequiresPermission('salla.integration.manage') exportNext() { return this.salla.exportNext(getTenantContext().tenantId); } @Get('connections') @RequiresPermission('salla.integration.view') connections() { return this.salla.listConnections(getTenantContext().tenantId); } @Get('branch-mappings') @RequiresPermission('salla.integration.view') mappings() { return this.salla.listBranchMappings(getTenantContext().tenantId); } @Get('products') @RequiresPermission('salla.integration.view') products() { return this.salla.listProducts(getTenantContext().tenantId); } @Get('orders') @RequiresPermission('salla.integration.view') orders() { return this.salla.listOrders(getTenantContext().tenantId); } @Get('export-log') @RequiresPermission('salla.integration.view') logs() { return this.salla.logs(getTenantContext().tenantId); } @Post('webhooks/:storeId/orders') webhook(@Param('storeId') storeId: string, @Headers('x-salla-signature') signature: string, @Req() req: Request, @Body() body: { event?: string; data?: { customer?: { name?: string; mobile?: string }; items?: Array<{ name?: string; quantity?: string; amount?: string }>; branchId?: string } }) { return this.salla.webhook(getTenantContext().tenantId, storeId, JSON.stringify(req.body), signature, body); } }
