import { Inject, Injectable } from '@nestjs/common';
import { and, desc, eq, isNull, sql } from 'drizzle-orm';
import { DomainError, newId } from '@erp/contracts';
import { boqTerms, progressBillLines, progressBills, projects, projectRequirements, projectStages, projectStageTemplates, tenantSettings, withTenantTx, type DatabaseHandle } from '@erp/database';

import { DATABASE_HANDLE } from '../../database/database.module.js';
import { SequencesService } from '../platform-services/index.js';
import { SalesService } from '../sales/sales.service.js';

import { computeProgressBill } from './progress-bill-calculator.js';

export type ProjectInput = { branchId?: string; code: string; name: string; partyId: string; contractorPartyId?: string; startsOn?: string; endsOn?: string; contractValue?: string; retentionPct?: string; costCenterId?: string; templateId?: string };
export type BoqInput = { code: string; description: string; qty?: string; unitValue: string; estimatedCost?: string; executionPeriod?: string };
export type BillInput = { billDate: string; lines: Array<{ termId: string; billPct?: string; billValue?: string }> };

@Injectable()
export class ProjectsService {
  constructor(@Inject(DATABASE_HANDLE) private readonly database: DatabaseHandle, private readonly sequences: SequencesService, private readonly sales: SalesService) {}
  async ensureEnabled(tenantId: string) { const [flag] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(tenantSettings).where(and(eq(tenantSettings.tenantId, tenantId), eq(tenantSettings.key, 'pack.projects'))).limit(1)); if (flag && flag.value !== true && flag.value !== 'true') throw new DomainError('NOT_FOUND', 'Projects pack is disabled for this tenant', 404); }
  async list(tenantId: string) { await this.ensureEnabled(tenantId); return { data: await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(projects).where(and(eq(projects.tenantId, tenantId), isNull(projects.deletedAt))).orderBy(desc(projects.createdAt))) }; }
  async create(tenantId: string, input: ProjectInput) { await this.ensureEnabled(tenantId); const id = newId(); await withTenantTx(this.database.db, tenantId, async (tx) => { await tx.insert(projects).values({ id, tenantId, branchId: input.branchId, code: input.code, name: input.name, partyId: input.partyId, contractorPartyId: input.contractorPartyId, startsOn: input.startsOn, endsOn: input.endsOn, contractValue: input.contractValue ?? '0', retentionPct: input.retentionPct ?? '0', costCenterId: input.costCenterId, status: 'active' }); if (input.templateId) { const [template] = await tx.select().from(projectStageTemplates).where(and(eq(projectStageTemplates.tenantId, tenantId), eq(projectStageTemplates.id, input.templateId))); const stages = Array.isArray(template?.stages) ? template.stages as Array<{ name?: string }> : []; if (stages.length) await tx.insert(projectStages).values(stages.map((stage, index) => ({ id: newId(), tenantId, projectId: id, name: stage.name ?? `Stage ${index + 1}`, stageOrder: index + 1 }))); } }); return this.read(tenantId, id); }
  async read(tenantId: string, id: string) { await this.ensureEnabled(tenantId); const [project] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(projects).where(and(eq(projects.tenantId, tenantId), eq(projects.id, id))).limit(1)); if (!project) throw new DomainError('NOT_FOUND', 'Project not found', 404); const [stages, boq, requirements] = await Promise.all([withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(projectStages).where(and(eq(projectStages.tenantId, tenantId), eq(projectStages.projectId, id)))), withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(boqTerms).where(and(eq(boqTerms.tenantId, tenantId), eq(boqTerms.projectId, id), isNull(boqTerms.deletedAt)))), withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(projectRequirements).where(and(eq(projectRequirements.tenantId, tenantId), eq(projectRequirements.projectId, id), isNull(projectRequirements.deletedAt))))]); return { data: { ...project, stages, boq, requirements } }; }
  async createTemplate(tenantId: string, input: { name: string; stages: Array<{ name: string }> }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(projectStageTemplates).values({ id: newId(), tenantId, name: input.name, stages: input.stages.map((stage, index) => ({ ...stage, order: index + 1 })) }).returning()); return row; }
  async addStage(tenantId: string, projectId: string, input: { name: string; stageOrder?: number }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(projectStages).values({ id: newId(), tenantId, projectId, name: input.name, stageOrder: input.stageOrder ?? 0 }).returning()); return row; }
  async accreditStage(tenantId: string, stageId: string, userId: string, note?: string) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.update(projectStages).set({ status: 'accredited', accreditedBy: userId, accreditedAt: new Date(), accreditationNote: note, updatedAt: new Date() }).where(and(eq(projectStages.tenantId, tenantId), eq(projectStages.id, stageId))).returning()); return row; }
  async addBoq(tenantId: string, projectId: string, input: BoqInput) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(boqTerms).values({ id: newId(), tenantId, projectId, code: input.code, description: input.description, qty: input.qty ?? '1', unitValue: input.unitValue, estimatedCost: input.estimatedCost ?? '0', executionPeriod: input.executionPeriod }).returning()); return row; }
  async createBill(tenantId: string, projectId: string, input: BillInput) { await this.ensureEnabled(tenantId); const project = (await this.read(tenantId, projectId)).data; const billId = newId(); const termIds = new Set(input.lines.map((line) => line.termId)); const terms = (project.boq as Array<typeof boqTerms.$inferSelect>).filter((term) => termIds.has(term.id)); const mapped = input.lines.map((line) => { const term = terms.find((item) => item.id === line.termId); if (!term) throw new DomainError('BOQ_TERM_NOT_FOUND', 'BOQ term not found', 404); return { termId: term.id, qty: term.qty, unitValue: term.unitValue, previouslyBilled: term.previouslyBilled, billPct: line.billPct, billValue: line.billValue }; }); const computed = computeProgressBill(mapped, project.retentionPct); await withTenantTx(this.database.db, tenantId, async (tx) => { const branchId = project.branchId; if (!branchId) throw new DomainError('PROJECT_BRANCH_REQUIRED', 'Project branch is required to number progress bills', 422); const allocated = await this.sequences.next({ tenantId, branchId, docType: 'progress_bill' }, tx, { prefix: 'PB-', padding: 6 }); await tx.insert(progressBills).values({ id: billId, tenantId, projectId, number: allocated.display, billDate: input.billDate, workValue: computed.workValue, previousValue: computed.previousValue, retentionValue: computed.retentionValue, netDue: computed.netDue, summary: { remainingAfter: computed.remainingAfter } }); await tx.insert(progressBillLines).values(computed.lines.map((line, index) => ({ billId, tenantId, lineNo: index + 1, termId: line.termId, billPct: line.billPct, billValue: line.billValue, previousValue: line.previousValue, remainingValue: line.remainingValue }))); }); return this.getBill(tenantId, billId); }
  async getBill(tenantId: string, billId: string) { const [bill] = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(progressBills).where(and(eq(progressBills.tenantId, tenantId), eq(progressBills.id, billId)))); if (!bill) throw new DomainError('PROGRESS_BILL_NOT_FOUND', 'Progress bill not found', 404); const lines = await withTenantTx(this.database.db, tenantId, (tx) => tx.select().from(progressBillLines).where(and(eq(progressBillLines.tenantId, tenantId), eq(progressBillLines.billId, billId)))); return { data: { ...bill, lines } }; }
  async postBill(tenantId: string, billId: string, input: { branchId?: string; fiscalPeriodId?: string; revenueAccountId?: string; receivableAccountId?: string; retentionReceivableAccountId?: string }) { await this.ensureEnabled(tenantId); const bill = (await this.getBill(tenantId, billId)).data; if (bill.status !== 'draft') throw new DomainError('PROGRESS_BILL_INVALID_STATE', 'Only draft progress bills can be posted', 409); const project = (await this.read(tenantId, bill.projectId)).data; const branchId = input.branchId ?? project.branchId; if (!branchId) throw new DomainError('PROJECT_BRANCH_REQUIRED', 'Project branch is required to post bill', 422); const invoice = await this.sales.create(tenantId, { branchId, partyId: project.partyId, kind: 'sale', lines: [{ description: `Progress bill ${bill.number ?? bill.id}`, quantity: '1', unitPrice: bill.netDue, taxRate: '0' }] }); await this.sales.post(tenantId, invoice.id, input.fiscalPeriodId && input.revenueAccountId && input.receivableAccountId ? { fiscalPeriodId: input.fiscalPeriodId, journalLines: [{ accountId: input.receivableAccountId, debit: bill.netDue, partyId: project.partyId }, { accountId: input.retentionReceivableAccountId ?? input.receivableAccountId, debit: bill.retentionValue, partyId: project.partyId }, { accountId: input.revenueAccountId, credit: bill.workValue }] } : {}); await withTenantTx(this.database.db, tenantId, async (tx) => { await tx.update(progressBills).set({ status: 'posted', invoiceId: invoice.id, postedAt: new Date(), updatedAt: new Date() }).where(and(eq(progressBills.tenantId, tenantId), eq(progressBills.id, billId))); for (const line of bill.lines) await tx.update(boqTerms).set({ previouslyBilled: sql`${boqTerms.previouslyBilled} + ${line.billValue}`, updatedAt: new Date() }).where(and(eq(boqTerms.tenantId, tenantId), eq(boqTerms.id, line.termId))); }); return this.getBill(tenantId, billId); }
  async releaseRetention(tenantId: string, billId: string, input: { branchId?: string }) { await this.ensureEnabled(tenantId); const bill = (await this.getBill(tenantId, billId)).data; if (bill.status !== 'posted') throw new DomainError('PROGRESS_BILL_INVALID_STATE', 'Only posted bills can release retention', 409); const project = (await this.read(tenantId, bill.projectId)).data; const branchId = input.branchId ?? project.branchId; if (!branchId) throw new DomainError('PROJECT_BRANCH_REQUIRED', 'Project branch is required', 422); const invoice = await this.sales.create(tenantId, { branchId, partyId: project.partyId, kind: 'sale', lines: [{ description: `Retention release ${bill.number ?? bill.id}`, quantity: '1', unitPrice: bill.retentionValue, taxRate: '0' }] }); await withTenantTx(this.database.db, tenantId, (tx) => tx.update(progressBills).set({ status: 'released', releasedAt: new Date(), updatedAt: new Date(), summary: sql`${progressBills.summary} || ${JSON.stringify({ retentionReleaseInvoiceId: invoice.id })}::jsonb` }).where(and(eq(progressBills.tenantId, tenantId), eq(progressBills.id, billId)))); return { data: { retentionReleaseInvoiceId: invoice.id } }; }
  async addRequirement(tenantId: string, input: { projectId?: string; partyId?: string; title: string; status?: string; payload?: Record<string, unknown> }) { await this.ensureEnabled(tenantId); const [row] = await withTenantTx(this.database.db, tenantId, (tx) => tx.insert(projectRequirements).values({ id: newId(), tenantId, projectId: input.projectId, partyId: input.partyId, title: input.title, status: input.status ?? 'open', payload: input.payload ?? {} }).returning()); return row; }
}
